import { PartConfig } from "../models/partConfig";

type SeedPartConfig = Omit<PartConfig, "createdAt" | "updatedAt">;

export const defaultPartConfigs: SeedPartConfig[] = [
    {
        partNumber: "EMVS353",
        legacyRfidPartNumber: "EMVS353",
        readingMode: "manual",
        isActive: true,
        notes: "Carga inicial del catalogo manual",
        usesLegacyRfidPayload: true,
    },
    {
        partNumber: "QVC-MSF8D-1",
        readingMode: "manual",
        isActive: true,
        notes: "Carga inicial del catalogo manual",
        usesLegacyRfidPayload: false,
    },
    {
        partNumber: "A2A00231",
        readingMode: "manual",
        isActive: true,
        notes: "Carga inicial del catalogo manual",
        usesLegacyRfidPayload: false,
    },
    {
        partNumber: "A74802",
        legacyRfidPartNumber: "A74802",
        readingMode: "manual",
        isActive: true,
        notes: "Carga inicial del catalogo manual",
        usesLegacyRfidPayload: true,
    },
    {
        partNumber: "A84962",
        legacyRfidPartNumber: "A84962",
        readingMode: "manual",
        isActive: true,
        notes: "Carga inicial del catalogo manual",
        usesLegacyRfidPayload: true,
    },
    {
        partNumber: "VSXLLM01",
        readingMode: "double_scan",
        rfidProgram: "VSXLL01",
        expectedGtin: "00851136001566",
        filterLabel: "902227",
        expectedLotLength: 9,
        isActive: true,
        notes: "Requiere dos codigos de barras",
        usesLegacyRfidPayload: false,
    },
    {
        partNumber: "VSXLLM02",
        readingMode: "double_scan",
        rfidProgram: "VSXLL01",
        expectedGtin: "00851136001566",
        filterLabel: "902227",
        expectedLotLength: 9,
        isActive: true,
        notes: "Requiere dos codigos de barras",
        usesLegacyRfidPayload: false,
    },
    {
        partNumber: "SEA3700",
        readingMode: "double_scan",
        rfidProgram: "VL-25",
        expectedGtin: "10884524001425",
        filterLabel: "P000027957",
        expectedLotLength: 9,
        isActive: true,
        notes: "Requiere dos codigos de barras",
        usesLegacyRfidPayload: false,
    },
    {
        partNumber: "C32-25-001",
        legacyRfidPartNumber: "CTVS353",
        readingMode: "single_scan",
        rfidProgram: "CTVS353",
        expectedGtin: "20845854081720",
        filterLabel: "903008",
        expectedLotLength: 9,
        isActive: true,
        notes: "Requiere un codigo de barras; payload legado por CTVS353",
        usesLegacyRfidPayload: true,
    },
];
